services:
  backend:
    build: .
    container_name: payment-gateway-api
    restart: always
    env_file: .env
    ports:
      - "8001:8001"
    mem_limit: 1g
    memswap_limit: 1g
    networks:
      - myapp_net

networks:
  myapp_net:
    driver: bridge